# Model Segmentation

Since, our main model has higher error margin for younger age group (18-25), around 93%, we can segment our model. This technique is known as Model Segmentation:
- Model A -> Younger age group (18-25)
- Model B -> Rest of the age groups

However, the remaining 7% will be moved to Model B, this might as well reduce their margin of error.

In [1]:
import pandas as pd

# Loading processed
df = pd.read_excel("D:/[01] SKILLS/[00] Projects/01 Healthcare Premium Prediction/data/raw/raw_premiums_data.xlsx")
df.head()

,Age,Gender,Region,Marital_status,Number Of Dependants,BMI_Category,Smoking_Status,Employment_Status,Income_Level,Income_Lakhs,Medical History,Insurance_Plan,Annual_Premium_Amount
0,26,Male,Northwest,Unmarried,0,Normal,No Smoking,Salaried,<10L,6,Diabetes,Bronze,9053
1,29,Female,Southeast,Married,2,Obesity,Regular,Salaried,<10L,6,Diabetes,Bronze,16339
2,49,Female,Northeast,Married,2,Normal,No Smoking,Self-Employed,10L - 25L,20,High blood pressure,Silver,18164
3,30,Female,Southeast,Married,3,Normal,No Smoking,Salaried,> 40L,77,No Disease,Gold,20303
4,18,Male,Northeast,Unmarried,0,Overweight,Regular,Self-Employed,> 40L,99,High blood pressure,Silver,13365

In [4]:
# Setting filter conditions
younger_grp_filter = df['Age'] <= 25
other_grp_filter = df['Age'] > 25

# Filtering Dataframe
df_younger_grp = df[younger_grp_filter]
df_other_grp = df[other_grp_filter ]

# Exporting Dataframes
df_younger_grp.to_excel(
    'D:/[01] SKILLS/[00] Projects/01 Healthcare Premium Prediction/data/raw/raw_premiums_data_young.xlsx'
)
df_other_grp.to_excel(
    'D:/[01] SKILLS/[00] Projects/01 Healthcare Premium Prediction/data/raw/raw_premiums_data_other.xlsx'
)